name: GFLUtils
version: '1.0'
main: social.gfl.MochaMilkie.GFLUtils.GFLUtils
api-version: '1.21'

permissions:
  GFLUtils.particletrail:
    description: Allows players to assign a custom particle trail. VIP Perk

commands:
  trail:
    description: Allows players with permission to assign a custom particle trail.
    usage: /trail
    permission: GFLUtils.particletrail
    permission-message: You do not have access to this command, if you feel this is an error contact Benroy. (GFLUtils.particletrail)
